# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HmBCj1g3s20jq6dpA6b5AElsYK5AtYDQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

df = pd.read_csv("SalesData.csv")
print("Initial Shape:", df.shape)
df.head()

# Remove duplicates
df = df.drop_duplicates()

# Handle missing values
missing_report = df.isnull().sum()
print("Missing values per column:\n", missing_report)
for col in df.columns:
    if df[col].dtype in [np.float64, np.int64]:
        df[col].fillna(df[col].mean(), inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)

# Standardize text columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.lower()

# Remove outliers using Z-score method
numeric_cols = df.select_dtypes(include=[np.number]).columns
df = df[(np.abs(stats.zscore(df[numeric_cols])) < 3).all(axis=1)]

print("Cleaned Shape:", df.shape)
df.head()

# Summary statistics
summary = df.describe().T
display(summary)

# Correlation matrix
corr = df.select_dtypes(include=[np.number]).corr()

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()